
import type { Product } from './types';

export const products: Omit<Product, 'price'>[] = [
  {
    id: 'prd_001',
    name: 'Acoustic Guitar',
    description: 'A beautifully crafted acoustic guitar with a rich, warm tone. Perfect for beginners and seasoned players alike.',
    manufacturer: 'Fender',
    partNumber: 'FA-125CE',
    codeName: 'AcousticGtr',
    mapping1: 'category:instruments',
    mapping2: 'style:dreadnought',
    mapping3: '',
    status: 'Available',
  },
  {
    id: 'prd_002',
    name: 'Wireless Headphones',
    description: 'Experience immersive sound with these high-fidelity wireless headphones. Featuring noise-cancellation technology and a 20-hour battery life.',
    manufacturer: 'Sony',
    partNumber: 'WH-1000XM4',
    codeName: 'WirelessHP',
    mapping1: 'category:electronics',
    mapping2: 'feature:noise-cancelling',
    mapping3: '',
    status: 'Available',
  },
  {
    id: 'prd_003',
    name: 'Modern Bookshelf',
    description: 'A sleek and sturdy bookshelf to organize your favorite reads. Made from sustainable bamboo with a minimalist design that fits any decor.',
    manufacturer: 'IKEA',
    partNumber: 'BILLY-789',
    codeName: 'BookMdn',
    mapping1: 'category:furniture',
    mapping2: 'material:bamboo',
    mapping3: '',
    status: 'Unavailable',
  },
  {
    id: 'prd_004',
    name: 'Espresso Machine',
    description: 'Brew cafe-quality espresso at home with this professional-grade machine. Features a powerful 15-bar pump and a built-in milk frother.',
    manufacturer: 'Breville',
    partNumber: 'BES870XL',
    codeName: 'EspressoM',
    mapping1: 'category:appliances',
    mapping2: 'feature:frother',
    mapping3: '',
    status: 'Available',
  },
  {
    id: 'prd_005',
    name: 'Leather Backpack',
    description: 'A stylish and durable backpack crafted from genuine leather. It has multiple compartments, including a padded laptop sleeve.',
    manufacturer: 'Herschel',
    partNumber: 'LTH-BP-01',
    codeName: 'LthrBP',
    mapping1: 'category:accessories',
    mapping2: 'material:leather',
    mapping3: '',
    status: 'Available',
  },
];
