
import type { Product } from './types';

export const products: Product[] = [
  {
    id: 'P1001001',
    name: 'Acoustic Guitar',
    description: 'A beautifully crafted acoustic guitar with a rich, warm tone. Perfect for beginners and seasoned players alike. Comes with a soft case and a set of picks.',
    price: 249.99,
    images: ['https://placehold.co/600x400.png', 'https://placehold.co/600x400.png', 'https://placehold.co/600x400.png'],
    category: 'Instruments',
    color: 'Natural',
    brand: 'Fender',
  },
  {
    id: 'P1001002',
    name: 'Wireless Headphones',
    description: 'Experience immersive sound with these high-fidelity wireless headphones. Featuring noise-cancellation technology and a 20-hour battery life.',
    price: 199.99,
    images: ['https://placehold.co/600x400.png', 'https://placehold.co/600x400.png', 'https://placehold.co/600x400.png'],
    category: 'Electronics',
    color: 'Black',
    brand: 'Sony',
  },
  {
    id: 'P1001003',
    name: 'Modern Bookshelf',
    description: 'A sleek and sturdy bookshelf to organize your favorite reads. Made from sustainable bamboo with a minimalist design that fits any decor.',
    price: 150.0,
    images: ['https://placehold.co/600x400.png', 'https://placehold.co/600x400.png', 'https://placehold.co/600x400.png'],
    category: 'Furniture',
    color: 'Bamboo',
    brand: 'IKEA',
  },
  {
    id: 'P1001004',
    name: 'Espresso Machine',
    description: 'Brew cafe-quality espresso at home with this professional-grade machine. Features a powerful 15-bar pump and a built-in milk frother.',
    price: 499.5,
    images: ['https://placehold.co/600x400.png', 'https://placehold.co/600x400.png', 'https://placehold.co/600x400.png'],
    category: 'Appliances',
    color: 'Silver',
    brand: 'Breville',
  },
  {
    id: 'P1001005',
    name: 'Leather Backpack',
    description: 'A stylish and durable backpack crafted from genuine leather. It has multiple compartments, including a padded laptop sleeve.',
    price: 120.0,
    images: ['https://placehold.co/600x400.png', 'https://placehold.co/600x400.png', 'https://placehold.co/600x400.png'],
    category: 'Accessories',
    color: 'Brown',
    brand: 'Herschel',
  },
  {
    id: 'P1001006',
    name: 'Yoga Mat',
    description: 'A non-slip, eco-friendly yoga mat providing excellent grip and cushioning. Made from natural rubber and comes with a carrying strap.',
    price: 45.0,
    images: ['https://placehold.co/600x400.png', 'https://placehold.co/600x400.png', 'https://placehold.co/600x400.png'],
    category: 'Sports',
    color: 'Teal',
    brand: 'Lululemon',
  },
  {
    id: 'P1001007',
    name: 'Smart Watch',
    description: 'Track your fitness, receive notifications, and more with this sleek smart watch. Compatible with both iOS and Android devices.',
    price: 299.0,
    images: ['https://placehold.co/600x400.png', 'https://placehold.co/600x400.png', 'https://placehold.co/600x400.png'],
    category: 'Electronics',
    color: 'Rose Gold',
    brand: 'Apple',
  },
  {
    id: 'P1001008',
    name: 'Electric Keyboard',
    description: 'A 61-key portable electric keyboard with hundreds of built-in sounds and rhythms. Ideal for learning and composing music.',
    price: 180.75,
    images: ['https://placehold.co/600x400.png', 'https://placehold.co/600x400.png', 'https://placehold.co/600x400.png'],
    category: 'Instruments',
    color: 'Black',
    brand: 'Yamaha',
  },
   {
    id: 'P1001009',
    name: 'Chef\'s Knife',
    description: 'A professional high-carbon stainless steel chef\'s knife. Perfectly balanced for precision cutting and dicing. An essential tool for any kitchen.',
    price: 89.99,
    images: ['https://placehold.co/600x400.png', 'https://placehold.co/600x400.png', 'https://placehold.co/600x400.png'],
    category: 'Kitchen',
    color: 'Silver',
    brand: 'Wüsthof',
  },
];
