import type { Product } from './types';

export const products: Product[] = [
  {
    id: 1,
    name: 'Acoustic Guitar',
    description: 'A beautifully crafted acoustic guitar with a rich, warm tone. Perfect for beginners and seasoned players alike. Comes with a soft case and a set of picks.',
    price: 249.99,
    image: 'https://placehold.co/600x400.png',
    category: 'Instruments',
  },
  {
    id: 2,
    name: 'Wireless Headphones',
    description: 'Experience immersive sound with these high-fidelity wireless headphones. Featuring noise-cancellation technology and a 20-hour battery life.',
    price: 199.99,
    image: 'https://placehold.co/600x400.png',
    category: 'Electronics',
  },
  {
    id: 3,
    name: 'Modern Bookshelf',
    description: 'A sleek and sturdy bookshelf to organize your favorite reads. Made from sustainable bamboo with a minimalist design that fits any decor.',
    price: 150.0,
    image: 'https://placehold.co/600x400.png',
    category: 'Furniture',
  },
  {
    id: 4,
    name: 'Espresso Machine',
    description: 'Brew cafe-quality espresso at home with this professional-grade machine. Features a powerful 15-bar pump and a built-in milk frother.',
    price: 499.5,
    image: 'https://placehold.co/600x400.png',
    category: 'Appliances',
  },
  {
    id: 5,
    name: 'Leather Backpack',
    description: 'A stylish and durable backpack crafted from genuine leather. It has multiple compartments, including a padded laptop sleeve.',
    price: 120.0,
    image: 'https://placehold.co/600x400.png',
    category: 'Accessories',
  },
  {
    id: 6,
    name: 'Yoga Mat',
    description: 'A non-slip, eco-friendly yoga mat providing excellent grip and cushioning. Made from natural rubber and comes with a carrying strap.',
    price: 45.0,
    image: 'https://placehold.co/600x400.png',
    category: 'Sports',
  },
  {
    id: 7,
    name: 'Smart Watch',
    description: 'Track your fitness, receive notifications, and more with this sleek smart watch. Compatible with both iOS and Android devices.',
    price: 299.0,
    image: 'https://placehold.co/600x400.png',
    category: 'Electronics',
  },
  {
    id: 8,
    name: 'Electric Keyboard',
    description: 'A 61-key portable electric keyboard with hundreds of built-in sounds and rhythms. Ideal for learning and composing music.',
    price: 180.75,
    image: 'https://placehold.co/600x400.png',
    category: 'Instruments',
  },
   {
    id: 9,
    name: 'Chef\'s Knife',
    description: 'A professional high-carbon stainless steel chef\'s knife. Perfectly balanced for precision cutting and dicing. An essential tool for any kitchen.',
    price: 89.99,
    image: 'https://placehold.co/600x400.png',
    category: 'Appliances',
  },
];
